### ISSUE TITLE
Assets not loading properly.

### ISSUE THREAD

**Issue by verygreenboi** [kyparn/fancybox2-rails#24]
I've loaded the gem on my Gemfile but when I run my app the fancybox assets do not appear to be loading. The css at least shows an empty comment block.

**Comment by diegosax** [comment]
Your problem @lb0202 is the you require fancybox before the jquery.
change from 
//= require fancybox
//= require jquery
//= require jquery_ujs
//= require twitter/bootstrap

to

//= require jquery
//= require jquery_ujs
//= require twitter/bootstrap
//= require fancybox

**Comment by rmm5t** [comment]
@diegosax, Thanks for chiming in to help @lb0202. :beers: 

@verygreenboi Does this solve your problem too? I'd like to close this issue out.

**Comment by verygreenboi** [comment]
Yes it does! Silly me. Thanks!

**Comment by brendon** [comment]
I'm having the same problem as @verygreenboi, I'm including the assets in the right order. What's loaded in the browser is:

fancybox.css
```
/*



 */
```

fancybox.js

Just a bunch of empty lines


In development, because those two files only have `requires` in them, and ?body=1 is being passed to them, they will of course be empty. The problem is that the required files aren't being loaded in separately by the asset pipeline though.

I'm using the latest version of 4.1.

**Comment by ACPK** [comment]
@brendon - I'm also having a problem with "Uncaught TypeError: $(...).fancybox is not a function".

**Comment by brendon** [comment]
@ACPK, shouldn't that be `$(...).fancybox();` closing parentheses? If it's not that, it looks like fancy box isn't loaded so you need to dig a bit deeper as to why that is. Are there any console logs?
